/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-sources/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Each dataset's source, last successful import and last attempt */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Building profile: details, evaluation summary, coverage notes and data freshness */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluations and permit milestones in one list, newest first
         * @description Each permit contributes up to three events: applied, issued and closed.
         */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}/permits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Building permits attached to a building, newest activity first
         * @description Only permits whose address matches this building and no other are returned. Each carries its match evidence. Permits can indicate maintenance, renovation or construction; they are not a judgement of the building.
         */
        get: operations["permits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All RentSafeTO evaluations for a building, newest first */
        get: operations["evaluations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How the latest evaluation compares with similar buildings
         * @description Peers are chosen by the first rule that yields at least 15 buildings. The rule, group size and spread are always returned; the percentile only when the group is large enough.
         */
        get: operations["comparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find buildings by address
         * @description Returns candidates, never a single silent guess. When `ambiguous` is true the client must ask the user to choose. `matchType` says how certain the match is.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DataSourceStatus: {
            datasets: components["schemas"]["Dataset"][];
            /** @description Attribution that must accompany the data */
            licence: string;
        };
        Dataset: {
            /** @example evaluations_v2023 */
            dataset: string;
            /** @example Apartment Building Evaluations (2023 – current) */
            title: string;
            /** @description The City's page for the dataset */
            portalUrl: string;
            /** @description False for archives the City no longer updates */
            updatedByCity: boolean;
            /** @description Null if the dataset has never been imported successfully */
            lastSuccessfulImport: components["schemas"]["DatasetImport"];
            /** @description The most recent attempt, successful or not */
            lastAttempt: components["schemas"]["ImportAttempt"];
            /**
             * Format: int32
             * @description Whole days since the last successful import; null if never
             */
            daysSinceSuccessfulImport: number;
        };
        DatasetImport: {
            /** Format: date-time */
            importedAt: string;
            /** @description The City's last-modified stamp for the file. It says when the portal file changed, not that every record in it is current. */
            sourceVersion: string;
            /** Format: int32 */
            recordCount: number;
        };
        ImportAttempt: {
            /** Format: date-time */
            startedAt: string;
            status: string;
        };
        BuildingLocation: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        BuildingSummary: {
            /** Format: int64 */
            id: number;
            /** @description RentSafeTO registration number (RSN) */
            rsn: string;
            address: string;
            /** @description Every address form this building is known by, e.g. each number of a range */
            knownAddresses: string[];
            postalFsa: string;
            ward: string;
            wardName: string;
            /** @description Null when the City published no coordinates */
            location: components["schemas"]["BuildingLocation"];
            /** Format: int32 */
            storeys: number;
            /** Format: int32 */
            units: number;
            /** Format: int32 */
            yearBuilt: number;
            /** Format: int32 */
            yearRegistered: number;
            /**
             * @description PRIVATE, TCHC or SOCIAL HOUSING
             * @example PRIVATE
             */
            propertyType: string;
            rentSafeRegistered: boolean;
            evaluations: components["schemas"]["EvaluationSummary"];
            permits: components["schemas"]["PermitSummary"];
            coverageNotes: ("BUILDING_NOT_UNIT" | "NOT_IN_CURRENT_REGISTRATION" | "NO_EVALUATIONS" | "SCORING_SYSTEM_CHANGED" | "ADDRESS_SHARED_WITH_OTHER_BUILDING" | "SOME_PERMITS_NOT_ATTACHED" | "NO_LOCATION")[];
            sources: components["schemas"]["SourceFreshness"][];
        };
        EvaluationPoint: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            score: number;
            /** @enum {string} */
            scoringVersion: "PRE_2023" | "V2023";
        };
        EvaluationSummary: {
            /** Format: int32 */
            count: number;
            countByScoringVersion: {
                [key: string]: number;
            };
            /** @description Null when the building has no evaluations */
            latest: components["schemas"]["EvaluationPoint"];
            /** @description The evaluation before latest under the same scoring version; null if none */
            previous: components["schemas"]["EvaluationPoint"];
            /**
             * Format: int32
             * @description latest.score - previous.score; null when there is no comparable previous
             */
            changeFromPrevious: number;
        };
        PermitSummary: {
            /**
             * Format: int32
             * @description Attached permits in the City's active-permits file
             */
            active: number;
            /**
             * Format: int32
             * @description Attached permits that are closed, cancelled or completed
             */
            cleared: number;
            /**
             * Format: int32
             * @description Active permits for new construction or demolition on the property
             */
            activeNewConstructionOrDemolition: number;
            /**
             * Format: date
             * @description Most recent issued (else application) date among attached permits; null if none
             */
            latestActivity: string;
        };
        SourceFreshness: {
            /** @example evaluations_v2023 */
            dataset: string;
            /**
             * Format: date-time
             * @description When LeaseLens last imported this dataset
             */
            lastImportedAt: string;
            /** @description The City's last-modified stamp for the file; not a guarantee of currency */
            sourceVersion: string;
        };
        TimelineEvaluation: {
            /** Format: int32 */
            score: number;
            /** @enum {string} */
            scoringVersion: "PRE_2023" | "V2023";
        };
        TimelineEvent: {
            /** Format: date */
            date: string;
            /**
             * @description DAY or MONTH: how exact `date` is (the scoring-system change is dated by month)
             * @enum {string}
             */
            datePrecision: "DAY" | "MONTH";
            /** @enum {string} */
            type: "EVALUATION" | "PERMIT_APPLIED" | "PERMIT_ISSUED" | "PERMIT_CLOSED" | "SCORING_SYSTEM_CHANGE";
            /**
             * @description Dataset the event comes from
             * @example permits_active
             */
            source: string;
            evaluation: components["schemas"]["TimelineEvaluation"];
            permit: components["schemas"]["TimelinePermit"];
        };
        TimelinePage: {
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            events: components["schemas"]["TimelineEvent"][];
        };
        TimelinePermit: {
            permitNumber: string;
            permitType: string;
            status: string;
            /** @enum {string} */
            listing: "ACTIVE" | "CLEARED";
            /** @enum {string} */
            workCategory: "ALTERATION_OR_REPAIR" | "NEW_CONSTRUCTION" | "DEMOLITION";
            siteRelation: string;
            description: string;
            predatesBuilding: boolean;
        };
        PermitMatch: {
            /** @description ADDRESS: same civic address; PERMIT_RANGE: the permit's address range covers it */
            method: string;
            /** @description HIGH or MEDIUM; only unambiguous matches are returned */
            confidence: string;
            /** @description BUILDING, NON_RESIDENTIAL_SPACE (a shop or office in or on the building), or OTHER_STRUCTURE_ON_SITE (e.g. townhouses on the same property) */
            siteRelation: string;
            /**
             * @description The permit's address as the City published it
             * @example 2721-2729 VICTORIA PARK AVE
             */
            permitAddress: string;
        };
        PermitPage: {
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            activeCount: number;
            /** Format: int32 */
            clearedCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            permits: components["schemas"]["PermitRecord"][];
        };
        PermitRecord: {
            permitNumber: string;
            revisionNumber: string;
            permitType: string;
            /**
             * @description ACTIVE: in the City's active-permits file; CLEARED: closed, cancelled or completed
             * @enum {string}
             */
            listing: "ACTIVE" | "CLEARED";
            /** @example Inspection */
            status: string;
            /**
             * @description Work on the existing building, or new construction / demolition on the site
             * @enum {string}
             */
            workCategory: "ALTERATION_OR_REPAIR" | "NEW_CONSTRUCTION" | "DEMOLITION";
            work: string;
            structureType: string;
            description: string;
            /** Format: date */
            applicationDate: string;
            /** Format: date */
            issuedDate: string;
            /** Format: date */
            completedDate: string;
            /** @description The applicant's estimate; null when the City's field holds no number */
            estimatedCost: number;
            /** Format: int32 */
            dwellingUnitsCreated: number;
            /** Format: int32 */
            dwellingUnitsLost: number;
            /** @description Applied for before the building's year built: likely about an earlier structure or this building's own construction */
            predatesBuilding: boolean;
            match: components["schemas"]["PermitMatch"];
            /** Format: date-time */
            importedAt: string;
        };
        EvaluationRecord: {
            /** Format: date */
            evaluationDate: string;
            /** @enum {string} */
            scoringVersion: "PRE_2023" | "V2023";
            /**
             * Format: int32
             * @description Overall score, 0-100. Only comparable with scores of the same scoringVersion
             */
            score: number;
            /**
             * Format: int32
             * @description V2023 only: score from the proactive (scheduled) evaluation
             */
            proactiveScore: number;
            /** Format: int32 */
            areasEvaluated: number;
            /** @description PRE_2023 only: the City's note on when the next evaluation is due */
            resultText: string;
            /**
             * Format: date-time
             * @description When LeaseLens last imported this record
             */
            importedAt: string;
        };
        Comparison: {
            /** Format: int64 */
            buildingId: number;
            /** @enum {string} */
            availability: "AVAILABLE" | "TOO_FEW_PEERS" | "NO_CURRENT_EVALUATION" | "MISSING_BUILDING_SIZE";
            /** @description The peer-selection rule used, with its parameters; null when no evaluation could be compared */
            rule: components["schemas"]["ComparisonRule"];
            /** Format: int32 */
            peerCount: number;
            /** Format: int32 */
            minimumPeers: number;
            /** @description The building's latest 2023+ evaluation; older-method scores are never compared */
            target: components["schemas"]["ComparisonScore"];
            /** @description Score spread among peers; null below minimumPeers */
            peerScores: components["schemas"]["ScoreSpread"];
            /**
             * Format: int32
             * @description Percent of peers with a lower score; null below minimumPeers
             * @example 62
             */
            percentOfPeersBelow: number;
            /**
             * Format: int32
             * @description Percent of peers with exactly the same score; null below minimumPeers
             */
            percentOfPeersEqual: number;
            permitActivity: components["schemas"]["ComparisonPermitActivity"];
            /**
             * Format: int32
             * @description Buildings that fit the size/location rule but have no 2023+ evaluation within the window, so were left out (the missing-data rate)
             */
            excludedWithoutRecentEvaluation: number;
            /** @description Property types in the peer group (PRIVATE, TCHC, SOCIAL HOUSING) */
            peerPropertyTypes: {
                [key: string]: number;
            };
        };
        ComparisonPermitActivity: {
            /**
             * Format: int32
             * @description Attached permits applied for in the last 5 years
             */
            building: number;
            /**
             * Format: double
             * @description Median of the same count across peers; null below minimumPeers
             */
            peerMedian: number;
            /** Format: double */
            peerUpperQuartile: number;
        };
        ComparisonRule: {
            /** @enum {string} */
            code: "SAME_WARD_SIMILAR_SIZE" | "SAME_WARD_BROADER_SIZE" | "WITHIN_3_KM_BROADER_SIZE";
            sameWard: boolean;
            /**
             * Format: int32
             * @description Peers within this distance; null when the rule uses the ward
             */
            radiusMetres: number;
            /**
             * Format: int32
             * @description Peers' unit count within ± this percent
             */
            unitsWithinPercent: number;
            /**
             * Format: int32
             * @description Peers' storey count within ± this many storeys
             */
            storeysWithin: number;
            /**
             * Format: int32
             * @description Peers' latest evaluation within this many days of the building's
             */
            evaluationWindowDays: number;
        };
        ComparisonScore: {
            /** Format: int32 */
            score: number;
            /** Format: date */
            date: string;
        };
        ScoreSpread: {
            /** Format: double */
            median: number;
            /** Format: double */
            lowerQuartile: number;
            /** Format: double */
            upperQuartile: number;
            /** Format: int32 */
            min: number;
            /** Format: int32 */
            max: number;
        };
        SearchResponse: {
            query: string;
            /**
             * @description How the results were found; the weakest method used decides how sure we are
             * @enum {string}
             */
            matchType: "ADDRESS" | "PREFIX" | "STREET" | "FUZZY" | "NONE";
            /** @description More than one building matched: ask the user to pick, never pick for them */
            ambiguous: boolean;
            /** @description More results exist than were returned; the user should refine the query */
            hasMore: boolean;
            results: components["schemas"]["SearchResult"][];
        };
        SearchResult: {
            /** Format: int64 */
            buildingId: number;
            /** @description RentSafeTO registration number, shown when buildings share an address */
            rsn: string;
            /** @example 181-183 GERRARD ST E */
            address: string;
            /**
             * @description The address form that matched the query
             * @example 183 GERRARD ST E
             */
            matchedAddress: string;
            wardName: string;
            /** Format: int32 */
            storeys: number;
            /** Format: int32 */
            units: number;
            rentSafeRegistered: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DataSourceStatus"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuildingSummary"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: {
                /** @description Event types to include; all when omitted */
                types?: ("EVALUATION" | "PERMIT_APPLIED" | "PERMIT_ISSUED" | "PERMIT_CLOSED" | "SCORING_SYSTEM_CHANGE")[];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimelinePage"];
                };
            };
        };
    };
    permits: {
        parameters: {
            query?: {
                /** @description active, cleared or all */
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PermitPage"];
                };
            };
        };
    };
    evaluations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EvaluationRecord"][];
                };
            };
        };
    };
    comparison: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Comparison"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Address, or part of one, e.g. "181 gerrard st e" or "123 blo" */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
